-- MySQL Script generated by MySQL Workbench
-- Sun Apr  5 22:10:17 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema Mybank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Mybank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Mybank` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accounts` (
  `id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `type_id` INT NULL,
  `amount` FLOAT NULL,
  PRIMARY KEY (`id`, `client_id`),
  INDEX `fk_cuentas_clientes_idx` (`client_id` ASC),
  CONSTRAINT `fk_cuentas_clientes`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`types_of_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`types_of_accounts` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`, `account_id`),
  INDEX `fk_tipos_de_cuentas_cuentas1_idx` (`account_id` ASC),
  CONSTRAINT `fk_tipos_de_cuentas_cuentas1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mybank`.`methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mybank`.`methods` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deposits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deposits` (
  `id` INT NOT NULL,
  `method_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `date` DATE NULL,
  `amount` FLOAT NULL,
  PRIMARY KEY (`id`, `method_id`, `account_id`),
  INDEX `fk_deposits_methods1_idx` (`method_id` ASC),
  INDEX `fk_deposits_accounts1_idx` (`account_id` ASC),
  CONSTRAINT `fk_deposits_methods1`
    FOREIGN KEY (`method_id`)
    REFERENCES `Mybank`.`methods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deposits_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transfers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transfers` (
  `id` INT NOT NULL,
  `origin_account_id` INT NOT NULL,
  `destination_account_id` INT NOT NULL,
  `date` DATE NULL,
  `amount` FLOAT NULL,
  PRIMARY KEY (`id`, `origin_account_id`, `destination_account_id`),
  INDEX `fk_transfers_accounts1_idx` (`origin_account_id` ASC),
  INDEX `fk_transfers_accounts2_idx` (`destination_account_id` ASC),
  CONSTRAINT `fk_transfers_accounts1`
    FOREIGN KEY (`origin_account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfers_accounts2`
    FOREIGN KEY (`destination_account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`withdrawals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`withdrawals` (
  `id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `amount` FLOAT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`, `account_id`),
  INDEX `fk_withdrawals_accounts1_idx` (`account_id` ASC),
  CONSTRAINT `fk_withdrawals_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `Mybank` ;

-- -----------------------------------------------------
-- Table `Mybank`.`others_bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mybank`.`others_bank` (
  `id_banks` INT NOT NULL AUTO_INCREMENT,
  `account_others_banks` INT(20) NOT NULL DEFAULT 00000000000000000000,
  PRIMARY KEY (`id_banks`, `account_others_banks`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mybank`.`Mybank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mybank`.`Mybank` (
  `id_banks` INT NOT NULL,
  INDEX `fk_Mybank_table11_idx` (`id_banks` ASC),
  PRIMARY KEY (`id_banks`),
  CONSTRAINT `fk_Mybank_table11`
    FOREIGN KEY (`id_banks`)
    REFERENCES `Mybank`.`others_bank` (`id_banks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mybank`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mybank`.`clients` (
  `id_clients` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `credential` INT NOT NULL,
  `mybank` INT NOT NULL,
  PRIMARY KEY (`id_clients`),
  UNIQUE INDEX `id_clients_UNIQUE` (`id_clients` ASC),
  UNIQUE INDEX `credential_UNIQUE` (`credential` ASC),
  INDEX `fk_clients_Mybank1_idx` (`mybank` ASC),
  CONSTRAINT `fk_clients_Mybank1`
    FOREIGN KEY (`mybank`)
    REFERENCES `Mybank`.`Mybank` (`id_banks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mybank`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mybank`.`accounts` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `id_client` INT NOT NULL,
  `balance` INT NOT NULL DEFAULT 0,
  `number_acount` INT(20) NOT NULL,
  `type_account` VARCHAR(45) NOT NULL DEFAULT 'corriente',
  UNIQUE INDEX `idcuentas_corrientes_UNIQUE` (`number_acount` ASC),
  INDEX `fk_cuentas_corrientes_clients_idx` (`id_client` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cuentas_corrientes_clients`
    FOREIGN KEY (`id_client`)
    REFERENCES `Mybank`.`clients` (`id_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mybank`.`cuentas_ahorros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mybank`.`cuentas_ahorros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cuentas_ahorros` INT NOT NULL,
  `id_clients_a` INT NOT NULL,
  UNIQUE INDEX `cuentas_ahorros_UNIQUE` (`cuentas_ahorros` ASC),
  INDEX `fk_cuentas_ahorros_clients1_idx` (`id_clients_a` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cuentas_ahorros_clients1`
    FOREIGN KEY (`id_clients_a`)
    REFERENCES `Mybank`.`clients` (`id_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mybank`.`movements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mybank`.`movements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL DEFAULT 0,
  `origin_account` INT(20) NULL DEFAULT NULL,
  `destiny_account` INT(20) NULL DEFAULT NULL,
  `type_movement` VARCHAR(45) NOT NULL,
  `account_3ro(transfers)` INT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movements_1_idx` (`account_3ro(transfers)` ASC),
  INDEX `fk_movements_2_idx` (`origin_account` ASC, `destiny_account` ASC),
  CONSTRAINT `fk_movements_1`
    FOREIGN KEY (`account_3ro(transfers)`)
    REFERENCES `Mybank`.`others_bank` (`account_others_banks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movements_2`
    FOREIGN KEY (`origin_account` , `destiny_account`)
    REFERENCES `Mybank`.`accounts` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mybank`.`operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mybank`.`operations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_operation` VARCHAR(45) NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`, `type_operation`, `amount`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
